"""add_cafe_kitchen_to_business_type

Revision ID: 6af6d01f7b44
Revises: d7c185448a11
Create Date: 2025-12-19 02:01:03.376568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af6d01f7b44'
down_revision: Union[str, Sequence[str], None] = 'd7c185448a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
