"""Add AI features

Revision ID: 9e9d49645017
Revises: ec1025c712c7
Create Date: 2025-12-15 22:51:43.246483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e9d49645017'
down_revision: Union[str, Sequence[str], None] = 'ec1025c712c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('ai_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('processed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('embedding_vector', sa.ARRAY(sa.Float()), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'embedding_vector')
    op.drop_column('products', 'sku')
    op.drop_column('invoices', 'processed_data')
    op.drop_column('invoices', 'raw_text')
    op.drop_column('invoices', 'image_url')
    op.drop_column('customers', 'ai_preferences')
    # ### end Alembic commands ###
