"""add_min_margin_to_tenant

Revision ID: 46246b2d78be
Revises: 32387b0a5776
Create Date: 2025-12-19 01:49:46.255798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46246b2d78be'
down_revision: Union[str, Sequence[str], None] = '32387b0a5776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('min_margin_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'min_margin_percent')
    # ### end Alembic commands ###
