"""add_user_settings_field

Revision ID: 58d694ffff18
Revises: 6af6d01f7b44
Create Date: 2025-12-19 02:17:26.150694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58d694ffff18'
down_revision: Union[str, Sequence[str], None] = '6af6d01f7b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_v2', sa.Column('recipe', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('user_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_settings')
    op.drop_column('products_v2', 'recipe')
    # ### end Alembic commands ###
