"""add_scanned_receipt_tables

Revision ID: 688e393a4619
Revises: 3d375b5b6f96
Create Date: 2025-12-08 03:23:15.826533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688e393a4619'
down_revision: Union[str, Sequence[str], None] = '3d375b5b6f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanned_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='receiptstatus'), nullable=True),
    sa.Column('ai_response', sa.JSON(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanned_receipts_id'), 'scanned_receipts', ['id'], unique=False)
    op.create_table('scanned_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('matched_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['scanned_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanned_receipt_items_id'), 'scanned_receipt_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanned_receipt_items_id'), table_name='scanned_receipt_items')
    op.drop_table('scanned_receipt_items')
    op.drop_index(op.f('ix_scanned_receipts_id'), table_name='scanned_receipts')
    op.drop_table('scanned_receipts')
    # ### end Alembic commands ###
