"""add_ai_brain_columns

Revision ID: d7c185448a11
Revises: 46246b2d78be
Create Date: 2025-12-19 01:54:39.937952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7c185448a11'
down_revision: Union[str, Sequence[str], None] = '46246b2d78be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('velocity_score', sa.Float(), nullable=True))
    op.add_column('product_variants', sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'embedding_vector')
    op.drop_column('product_variants', 'velocity_score')
    # ### end Alembic commands ###
