"""add_organization_multi_tenant_support

Revision ID: e549f520a309
Revises: 801c8abbf208
Create Date: 2025-12-09 17:35:53.007639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e549f520a309'
down_revision: Union[str, Sequence[str], None] = '801c8abbf208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create organizations table first
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    
    # Create default organization for existing data
    op.execute("""
        INSERT INTO organizations (name, description, is_active, created_at, updated_at)
        VALUES ('Default Organization', 'Default organization for existing data', true, NOW(), NOW())
    """)
    
    # Check if invoicestatus enum exists, create if not
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE invoicestatus AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Create invoices table using existing enum type
    op.execute("""
        CREATE TABLE invoices (
            id SERIAL PRIMARY KEY,
            supplier_name VARCHAR,
            organization_id INTEGER NOT NULL,
            total_amount DOUBLE PRECISION,
            status invoicestatus,
            created_at TIMESTAMP,
            FOREIGN KEY (organization_id) REFERENCES organizations(id)
        )
    """)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('product_name_raw', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    # Add organization_id columns (nullable first, then set default, then make not null)
    op.add_column('branches', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.execute("UPDATE branches SET organization_id = (SELECT id FROM organizations LIMIT 1)")
    op.alter_column('branches', 'organization_id', nullable=False)
    op.create_index(op.f('ix_branches_organization_id'), 'branches', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'branches', 'organizations', ['organization_id'], ['id'])
    
    op.add_column('customers', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_index('ix_customers_phone', table_name='customers')
    op.execute("UPDATE customers SET organization_id = (SELECT id FROM organizations LIMIT 1)")
    op.alter_column('customers', 'organization_id', nullable=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'organizations', ['organization_id'], ['id'])
    
    op.add_column('products', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_index('ix_products_barcode', table_name='products')
    op.execute("UPDATE products SET organization_id = (SELECT id FROM organizations LIMIT 1)")
    op.alter_column('products', 'organization_id', nullable=False)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'products', 'organizations', ['organization_id'], ['id'])
    
    op.add_column('sales', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.execute("UPDATE sales SET organization_id = (SELECT id FROM organizations LIMIT 1)")
    op.alter_column('sales', 'organization_id', nullable=False)
    op.create_index(op.f('ix_sales_organization_id'), 'sales', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'organizations', ['organization_id'], ['id'])
    
    op.add_column('scanned_receipts', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.execute("UPDATE scanned_receipts SET organization_id = (SELECT id FROM organizations LIMIT 1)")
    op.alter_column('scanned_receipts', 'organization_id', nullable=False)
    op.create_index(op.f('ix_scanned_receipts_organization_id'), 'scanned_receipts', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'scanned_receipts', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'scanned_receipts', type_='foreignkey')
    op.drop_index(op.f('ix_scanned_receipts_organization_id'), table_name='scanned_receipts')
    op.drop_column('scanned_receipts', 'organization_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_column('sales', 'organization_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    op.drop_column('products', 'organization_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.drop_column('customers', 'organization_id')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_index(op.f('ix_branches_organization_id'), table_name='branches')
    op.drop_column('branches', 'organization_id')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
