"""add_payme_click_payment_methods

Revision ID: ec1025c712c7
Revises: e549f520a309
Create Date: 2025-12-09 18:25:51.958102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1025c712c7'
down_revision: Union[str, Sequence[str], None] = 'e549f520a309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new payment methods to enum
    op.execute("ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'payme'")
    op.execute("ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'click'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
